spring:
  application:
    name: Cateringhub
  app:
    jwtSecret: "mysupersecretkeythatshouldbeatleast32characterslong"
    jwtExpirationMs: 1000   # 1 hour in milliseconds

  datasource:
    url: jdbc:postgresql://localhost:5434/cateringhub
    username: admin
    password: pass1

  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        show_sql: true

logging:
  level:
    org.springframework.web: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,httptrace,beans
  endpoint:
    health:
      show-details: always
